// Mocks generated by Mockito 5.4.6 from annotations
// in leadloq/test/sorting_all_types_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:leadloq/features/leads/data/datasources/leads_remote_datasource.dart'
    as _i4;
import 'package:leadloq/features/leads/data/models/lead_model.dart' as _i3;
import 'package:leadloq/features/leads/data/models/paginated_response.dart'
    as _i2;
import 'package:leadloq/features/leads/domain/usecases/browser_automation_usecase.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePaginatedResponse_0<T> extends _i1.SmartFake
    implements _i2.PaginatedResponse<T> {
  _FakePaginatedResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLeadModel_1 extends _i1.SmartFake implements _i3.LeadModel {
  _FakeLeadModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LeadsRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLeadsRemoteDataSource extends _i1.Mock
    implements _i4.LeadsRemoteDataSource {
  MockLeadsRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i3.LeadModel>> getLeads({
    String? status,
    String? search,
    bool? candidatesOnly,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLeads,
          [],
          {
            #status: status,
            #search: search,
            #candidatesOnly: candidatesOnly,
          },
        ),
        returnValue: _i5.Future<List<_i3.LeadModel>>.value(<_i3.LeadModel>[]),
      ) as _i5.Future<List<_i3.LeadModel>>);

  @override
  _i5.Future<_i2.PaginatedResponse<_i3.LeadModel>> getLeadsPaginated({
    required int? page,
    required int? perPage,
    String? status,
    String? search,
    bool? candidatesOnly,
    String? sortBy,
    bool? sortAscending,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLeadsPaginated,
          [],
          {
            #page: page,
            #perPage: perPage,
            #status: status,
            #search: search,
            #candidatesOnly: candidatesOnly,
            #sortBy: sortBy,
            #sortAscending: sortAscending,
          },
        ),
        returnValue: _i5.Future<_i2.PaginatedResponse<_i3.LeadModel>>.value(
            _FakePaginatedResponse_0<_i3.LeadModel>(
          this,
          Invocation.method(
            #getLeadsPaginated,
            [],
            {
              #page: page,
              #perPage: perPage,
              #status: status,
              #search: search,
              #candidatesOnly: candidatesOnly,
              #sortBy: sortBy,
              #sortAscending: sortAscending,
            },
          ),
        )),
      ) as _i5.Future<_i2.PaginatedResponse<_i3.LeadModel>>);

  @override
  _i5.Future<_i3.LeadModel> getLead(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getLead,
          [id],
        ),
        returnValue: _i5.Future<_i3.LeadModel>.value(_FakeLeadModel_1(
          this,
          Invocation.method(
            #getLead,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.LeadModel>);

  @override
  _i5.Future<_i3.LeadModel> updateLead(_i3.LeadModel? lead) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLead,
          [lead],
        ),
        returnValue: _i5.Future<_i3.LeadModel>.value(_FakeLeadModel_1(
          this,
          Invocation.method(
            #updateLead,
            [lead],
          ),
        )),
      ) as _i5.Future<_i3.LeadModel>);

  @override
  _i5.Future<_i3.LeadModel> updateTimelineEntry(
    String? leadId,
    String? entryId,
    Map<String, dynamic>? updates,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTimelineEntry,
          [
            leadId,
            entryId,
            updates,
          ],
        ),
        returnValue: _i5.Future<_i3.LeadModel>.value(_FakeLeadModel_1(
          this,
          Invocation.method(
            #updateTimelineEntry,
            [
              leadId,
              entryId,
              updates,
            ],
          ),
        )),
      ) as _i5.Future<_i3.LeadModel>);

  @override
  _i5.Future<void> addTimelineEntry(
    String? leadId,
    Map<String, dynamic>? entryData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTimelineEntry,
          [
            leadId,
            entryData,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String> startAutomation(_i6.BrowserAutomationParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #startAutomation,
          [params],
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #startAutomation,
            [params],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<Map<String, dynamic>> getJobStatus(String? jobId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getJobStatus,
          [jobId],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<int> deleteMockLeads() => (super.noSuchMethod(
        Invocation.method(
          #deleteMockLeads,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<Map<String, dynamic>> recalculateConversionScores() =>
      (super.noSuchMethod(
        Invocation.method(
          #recalculateConversionScores,
          [],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<void> deleteLead(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteLead,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteLeads(List<String>? ids) => (super.noSuchMethod(
        Invocation.method(
          #deleteLeads,
          [ids],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
