version: '3.8'

services:
  leadloq-api:
    build: ./server
    container_name: leadloq-api
    ports:
      - "8000:8000"
    volumes:
      - ./server/db:/app/db
      - ./server/screenshots:/app/screenshots
    environment:
      - PYTHONUNBUFFERED=1
      - USE_DOCKER=1
      - SELENIUM_HUB_URL=http://selenium-hub:4444/wd/hub
    restart: unless-stopped
    depends_on:
      - selenium-hub
    networks:
      - leadloq-network

  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4444:4444"
    environment:
      - GRID_MAX_SESSION=10
      - GRID_BROWSER_TIMEOUT=300
      - GRID_TIMEOUT=300
    networks:
      - leadloq-network

  selenium-node:
    image: selenium/node-chromium:latest
    shm_size: '2gb'
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_SESSION_TIMEOUT=300
    networks:
      - leadloq-network
    deploy:
      replicas: 3  # Start with 3 nodes, can scale with docker-compose up --scale selenium-node=10

networks:
  leadloq-network:
    driver: bridge