name: leadloq
description: Lead generation and management system for businesses without websites
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.9
  dio: ^5.4.0
  go_router: ^13.0.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  url_launcher: ^6.2.2
  web_socket_channel: ^2.4.0
  flutter_dotenv: ^6.0.0
  path_provider: ^2.1.2
  file_picker: ^6.1.1
  fl_chart: ^0.66.0
  cached_network_image: ^3.3.1
  add_2_calendar: ^3.0.1
  mailer: ^6.0.1
  enough_icalendar: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  mocktail: ^1.0.4
  flutter_launcher_icons: ^0.14.4
  path_provider_platform_interface: ^2.1.2
  plugin_platform_interface: ^2.1.8

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

flutter_launcher_icons:
  android: true
  ios: true
  macos:
    generate: true
    image_path: "assets/images/LeadLoq-with-background.png"
  image_path: "assets/images/LeadLoq-with-background.png"
  adaptive_icon_background: "#2ECC71"  # Money green background
  adaptive_icon_foreground: "assets/images/LeadLoq-logo.png"
  remove_alpha_ios: true
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/LeadLoq-with-background.png"
    background_color: "#2ECC71"
    theme_color: "#2ECC71"
