version: '3.8'

services:
  leadloq-api:
    build: .
    container_name: leadloq-api
    ports:
      - "8000:8000"
    volumes:
      - ./db:/app/db
      - ./screenshots:/app/screenshots
      - ./website_screenshots:/app/website_screenshots
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PYTHONUNBUFFERED=1
      - USE_DOCKER=1
      - SELENIUM_HUB_URL=http://selenium-chrome:4444/wd/hub
      - MAX_PARALLEL_SEARCHES=2  # Limit parallel browser sessions
    restart: unless-stopped
    depends_on:
      - selenium-chrome
    networks:
      - leadloq-network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G

  selenium-chrome:
    image: selenium/standalone-chromium:latest
    container_name: selenium-chrome
    ports:
      - "4444:4444"
      - "7900:7900"
    volumes:
      - ./screenshots:/screenshots
      - ./website_screenshots:/website_screenshots
    environment:
      - SE_NODE_MAX_SESSIONS=3  # Reduced from 10
      - SE_NODE_SESSION_TIMEOUT=120
      - SE_VNC_PASSWORD=secret
      - SE_NODE_MAX_INSTANCES=3  # Reduced from 10
      - SE_OPTS=--max-sessions 3
    shm_size: '4gb'
    restart: unless-stopped
    networks:
      - leadloq-network
    deploy:
      resources:
        limits:
          cpus: '4'  # Allow up to 4 cores
          memory: 4G
        reservations:
          cpus: '2'  # Guarantee 2 cores
          memory: 2G

networks:
  leadloq-network:
    driver: bridge
